server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: accountModule
          uri: lb://account-microservice
          predicates:
            - Path=/account/**
        - id: searchModule
          uri: lb://search-microservice
          predicates:
            - Path=/search/**
        - id: restauranteModule
          uri: lb://restaurante-microservice
          predicates:
            - Path=/restaurante/**
        - id: reservationModule
          uri: lb://reservation-microservice
          predicates:
            - Path=/reservation/**
        - id: messagingModule
          uri: lb://messaging-microservice
          predicates:
            - Path=/messaging/**

